### ISSUE TITLE
IndexError: too many indices for array on_batch_end     loss = loss.data.cpu().numpy()[0]

### ISSUE THREAD

**Issue by danieleewww** [neptune-ml/data-science-bowl-2018#44]
execute neptune run main.py -- train_evaluate_predict_pipeline --pipeline_n
ame unet with the following error:

"/data-science-bowl-2018-master/steps/pytorch/callbacks.py", line 129, in on_batch_end
    loss = loss.data.cpu().numpy()[0]
IndexError: too many indices for array
Sentry is attempting to send 1 pending error messages"

> warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
2018-03-12 06-17-26 steps >>> starting training...
2018-03-12 06-17-26 steps >>> initial lr: 0.0001
2018-03-12 06-17-26 steps >>> epoch 0 ...
Traceback (most recent call last):
  File "/home/danieleewww/anaconda3/envs/python35/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 113, in <module>
    execute()
  File "/home/danieleewww/anaconda3/envs/python35/lib/python3.5/site-packages/deepsense/neptune/job_wrapper.py", line 109, in execute
    execfile(job_filepath, job_globals)
  File "/home/danieleewww/anaconda3/envs/python35/lib/python3.5/site-packages/past/builtins/misc.py", line 82, in execfile
    exec_(code, myglobals, mylocals)
  File "main.py", line 181, in <module>
    action()
  File "/home/danieleewww/anaconda3/envs/python35/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/danieleewww/anaconda3/envs/python35/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/danieleewww/anaconda3/envs/python35/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/danieleewww/anaconda3/envs/python35/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/danieleewww/anaconda3/envs/python35/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "main.py", line 153, in train_evaluate_predict_pipeline
    _train_pipeline(pipeline_name, validation_size)
  File "main.py", line 80, in _train_pipeline
    pipeline.fit_transform(data)
  File "/home/danieleewww/Documents/DSB2018/data-science-bowl-2018-master/steps/base.py", line 92, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/home/danieleewww/Documents/DSB2018/data-science-bowl-2018-master/steps/base.py", line 92, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/home/danieleewww/Documents/DSB2018/data-science-bowl-2018-master/steps/base.py", line 92, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/home/danieleewww/Documents/DSB2018/data-science-bowl-2018-master/steps/base.py", line 92, in fit_transform
    step_inputs[input_step.name] = input_step.fit_transform(data)
  File "/home/danieleewww/Documents/DSB2018/data-science-bowl-2018-master/steps/base.py", line 98, in fit_transform
    step_output_data = self._cached_fit_transform(step_inputs)
  File "/home/danieleewww/Documents/DSB2018/data-science-bowl-2018-master/steps/base.py", line 109, in _cached_fit_transform
    step_output_data = self.transformer.fit_transform(**step_inputs)
  File "/home/danieleewww/Documents/DSB2018/data-science-bowl-2018-master/steps/base.py", line 241, in fit_transform
    self.fit(*args, **kwargs)
  File "/home/danieleewww/Documents/DSB2018/data-science-bowl-2018-master/steps/pytorch/models.py", line 64, in fit
    self.callbacks.on_batch_end(metrics=metrics)
  File "/home/danieleewww/Documents/DSB2018/data-science-bowl-2018-master/steps/pytorch/callbacks.py", line 98, in on_batch_end
    callback.on_batch_end(*args, **kwargs)
  File "/home/danieleewww/Documents/DSB2018/data-science-bowl-2018-master/steps/pytorch/callbacks.py", line 129, in on_batch_end
    loss = loss.data.cpu().numpy()[0]
IndexError: too many indices for array
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
Press Ctrl-C to quit
Calculated experiment snapshot size: 351.43 MB  
Process exited with return code 1.

**Comment by danieleewww** [comment]
Some it's working without index error now now by uninstall pytorch(0.4.0 built from source) and install pytorch(0.3.0) with "conda install pytorch torchvision cuda91 -c pytorch" and pip uninstall pillow . pip install pillow --no-cache-dir

**Comment by kamil-kaczmarek** [comment]
Hi @danieleewww,

1. I run it with PyTorch 0.2 and it works fine. Is it stable with PyTorch 0.3?
2. Your  `Calculated experiment snapshot size: 351.43 MB` is quite big. Make sure that you do not have any additional files in your repo.
3. Pull latest `master` ;-)

Best,
Kamil

**Comment by kamil-kaczmarek** [comment]
closing this.

**Comment by carbonox-infernox** [comment]
If anyone else sees this, it can be fixed by deleting [0] from the end of 

loss = loss.data.cpu().numpy()[0]
